### ISSUE TITLE
CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by adefaria** [HaveAGitGat/Tdarr#666] opened 2022-07-25 00:28 UTC
Now that I finally converted all of my videos using Tdarr I like how I can leave it running and when new videos are downloaded it compresses them. And this works... But then it dies with "CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected". Now I've configured my Docker container to run Tdarr using Nvidia and I have properly configured it so that that works. But then it breaks with that error. The solution is simply to restart the Docker container and then re-queue the videos but why does it break in the first place?

[QjALSDImR-log.txt](https://github.com/HaveAGitGat/Tdarr/files/9177058/QjALSDImR-log.txt)

**Comment by adefaria** [comment] 2022-08-02 22:11
Another data point. When transcode fails in the docker container I can replicate the ffmpeg command on the desktop (IOW outside of the docker container) and it works fine. 

Why does it break in the docker container?

**Comment by HaveAGitGat** [comment] 2022-08-08 23:44
Hmm seems like a bug between FFmpeg/Docker/Hardware, perhaps an FFmpeg update will fix the issue. The dev container has an FFmpeg update, looking to get it out soon.

**Comment by adefaria** [comment] 2022-08-09 03:17
I can try out the new version when it becomes available. I was suspecting it may be the Nvidia for Cocker containers (I have a foggy memory of installing that to get GPU transcoding to work in a Docker container) and something there broke down causing the CUDA_ERROR_NO_DEVICE. Lately, I'm seeing it just about transcodes a video or two and suddenly there are no devices left to GPU transcode. Restarting the Docker container always fixes the problem but it's essentially babysitting Tdarr, which shouldn't have to be the case.

**Comment by Sc0th** [comment] 2022-08-18 06:47
FWIW I am seeing this exact behavior, happy to supply logs/test if it helps at all, a restart of the docker fixes it every time.

**Comment by Sc0th** [comment] 2022-08-19 00:05
Apologies, I could have made that post slightly more useful!

I also tried the automated reboot, also to no avail. I am running the docker using podman on a VM running on Proxmox with PCI pass-through.

Some (maybe) useful detail:

GPU - Nvidia 1050 Ti
Proxmox 72.-7

Linux infra01 4.18.0-372.19.1.el8_6.x86_64 #1 SMP Tue Aug 2 13:42:59 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
AlmaLinux 8.6 (Sky Tiger)

nvidia-container-toolkit-1.10.0-1.x86_64
kmod-nvidia-515.65.01-1.el8_6.elrepo.x86_64

podman run --name tdarr-node -v /appdata01/INFRA/tdarr-node/configs:/app/configs -v /appdata01/INFRA/tdarr-node/logs:/app/logs -v /MEDIA:/media -v /appdata01/PROD/tdarr/transcode:/transcode -e "nodeID=infra01-tdar
r-node"  -e "serverIP=x.x.x.x" -e "serverPort=8266" --net=host -e PUID=1000 -e PGID=1000 -e "NVIDIA_DRIVER_CAPABILITIES=all" -e "NVIDIA_VISIBLE_DEVICES=all" --gpus=all -d ghcr.io/haveagitgat/tdarr_node'

Tdarr Server & Node 2.00.18

--

I am using the following line monitored by Zabbix to alert me when it gets stuck:

cat /appdata01/PROD/tdarr/conf/server/Tdarr/DB2/StatisticsJSONDB/*.json | jq . | grep -ic err,wait

A result higher than 0 indicates it's got stuck, I did look at using this to 'self heal' by restating the docker on trigger, however the jobs do not appear to requeue automatically so that did not quite go to plan.

I wait with greatful anticipation of the next release with hope of a fix!

**Comment by adefaria** [comment] 2022-08-19 03:56
Yeah, I think that it will end up being some interaction between Tdarr and the Nvidia runtime for the Docker container that causes Nvidia to lose track of available devices thus reporting NO_CUDA_DEVICE.

I'm running on my Thelio desktop running Ubuntu 22.04. I have the following:
```
Earth:apt list| grep nvidia-container

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libnvidia-container-dev/bionic 1.10.0-1 amd64
libnvidia-container-tools/bionic,now 1.10.0-1 amd64 [installed,automatic]
libnvidia-container1-dbg/bionic 1.10.0-1 amd64
libnvidia-container1/bionic,now 1.10.0-1 amd64 [installed,automatic]
nvidia-container-runtime/bionic 3.10.0-1 all
nvidia-container-toolkit/bionic,now 1.10.0-1 amd64 [installed]
Earth:
```

**Comment by adefaria** [comment] 2022-08-23 16:44
Still have this issue however today I think I captured a log of Tdarr working on a video when the CUDA_ERROR_NO_DEVICE happened right in the middle. Maybe this log will help in debugging this bug
.
[to7uvYRwN-log.txt](https://github.com/HaveAGitGat/Tdarr/files/9404545/to7uvYRwN-log.txt)
.

**Comment by Lebo77** [comment] 2022-08-27 20:47
I am trying downgrading nvidia-docker2 back to 2.10.0-1 from 2.11.0-1 and seeing if that makes any difference as a workaround. If not I may try 2.9.1-1. 

I am having this same issue on Ubuntu 22.04 LTS.

**Comment by Lebo77** [comment] 2022-08-28 23:44
Downgrading to the nvidia-docker2 version 2.9.1-1 seems to be a workaround to this issue, at least in the day of testing. If it STOPS working I will let you know.

Annoying to have my updates reporting a heald-back package, but better than Tdarr-node breaking every hour or two.

**Comment by HaveAGitGat** [comment] 2022-08-28 23:47
Ok thanks for the update 👍

**Comment by adefaria** [comment] 2022-08-29 00:36
Thanks. Downgraded to 2.9.1-1. Will report what happens.

**Comment by Sc0th** [comment] 2022-08-29 00:48
You have seen this 'With the release of Docker 19.03, usage of nvidia-docker2 packages is deprecated since NVIDIA GPUs are now natively supported as devices in the Docker runtime.' here: - https://docs.nvidia.com/ai-enterprise/deployment-guide/dg-docker.html ?

I am using podman, with 👍 

```
nvidia-container-toolkit-1.10.0-1.x86_64
nvidia-x11-drv-515.65.01-1.el8_6.elrepo.x86_64
libnvidia-container1-1.10.0-1.x86_64
nvidia-x11-drv-libs-515.65.01-1.el8_6.elrepo.x86_64
libnvidia-container-tools-1.10.0-1.x86_64
kmod-nvidia-515.65.01-1.el8_6.elrepo.x86_64
```

And am seeing the same issue.

**Comment by adefaria** [comment] 2022-08-29 00:49
So are you saying I can just remove nvidia-docker2 and restart the docker container and it'll all work?

**Comment by Sc0th** [comment] 2022-08-29 00:55
That would depend on the version of docker you are running.

**Comment by adefaria** [comment] 2022-08-29 00:56
```
Earth:apt list | grep ^docker

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

docker-clean/jammy,jammy 2.0.4-4 all
docker-compose/jammy,jammy 1.29.2-1 all
docker-doc/jammy,jammy 20.10.12-0ubuntu4 all
docker-registry/jammy 2.8.0+ds1-4 amd64
docker.io/jammy,now 20.10.12-0ubuntu4 amd64 [installed]
docker2aci/jammy 0.17.2+dfsg-2.1 amd64
docker/jammy,jammy 1.5-2 all
Earth:
```

**Comment by adefaria** [comment] 2022-08-29 01:15
```
Earth:apt list --installed | grep -i docker

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

docker.io/jammy,now 20.10.12-0ubuntu4 amd64 [installed]
nvidia-docker2/bionic,now 2.9.1-1 all [installed,upgradable to: 2.11.0-1]
Earth:
```
The [installed] marks these as installed. Note the downgrade of nvidia-docker2 to 2.9.1-1 from 2.11.0-1.

**Comment by Sc0th** [comment] 2022-08-29 01:17
Apologies, noticed that a little late, I have downgraded my installs by one release also, see if it has any impact...

```
nvidia-x11-drv-515.65.01-1.el8_6.elrepo.x86_64
libnvidia-container-tools-1.9.0-1.x86_64
libnvidia-container1-1.9.0-1.x86_64
nvidia-x11-drv-libs-515.65.01-1.el8_6.elrepo.x86_64
kmod-nvidia-515.65.01-1.el8_6.elrepo.x86_64
nvidia-container-toolkit-1.9.0-1.x86_64
```

```
podman version 4.1.1
```

🤞

**Comment by Lebo77** [comment] 2022-08-29 03:29
OK, I think I have got it working WITHOUT the nvidia-docker2 package at all.

It requires a docker-compose update to 1.29 and a ver. 20 of docker itself to use the built-in NVIDIA functionality.

Docker-compose needs to be modified to let it know about the GPU(s):

```
 tdarr-node:
        container_name: tdarr-node
        image: haveagitgat/tdarr_node:latest
        restart: unless-stopped
        network_mode: service:tdarr
#        runtime: nvidia # Comment this out. Not needed with the built-in NVIDIA support
        deploy: # ADD this section
          resources:
            reservations:
              devices:
                - capabilities: [gpu]
        environment:
            - TZ=America/New_York
            - PUID=1000
            - PGID=1000
            - UMASK_SET=002
            - nodeID=Odin
            - nodeIP=0.0.0.0
            - nodePort=8267
            - serverIP=0.0.0.0
            - serverPort=8266
            - NVIDIA_VISIBLE_DEVICES=all # Not sure if these are still needed
            - NVIDIA_DRIVER_CAPABILITIES=all
        volumes:
            - <Your volumes here>
        depends_on:
            - tdarr
```
So far (just an hour and 3-4 transcodes) the GPU is still working in the node. 

Thanks for St0th for pointing out that nvidia-docker2 was deprecated. Recommend that examples and documentation be updated to match the new approach and eliminate the need for nvidia-docker2, at least on newer versions of docker.

**Comment by adefaria** [comment] 2022-08-29 14:10
How are you verifying that the GPUs are being used? I ask because I had to compile up nvtop to monitor GPU usage.

Also, when I recreate my Tdarr_node docker image it basically does a chown  for like an hour which I find useless because it seems to be doing chown on the database to set the owner to 1000:1000 but with 31k entries in the database from my transcoding my entire library, it takes like an hour before this process stops and the Tdarr_node is registered.

![Screenshot at 2022-08-29 07-06-18](https://user-images.githubusercontent.com/2692127/187220966-931f2360-32a4-4ad6-9d22-8cbb9e3a179b.png)

Do you experience this too?

**Comment by Lebo77** [comment] 2022-08-29 17:25
> How are you verifying that the GPUs are being used? I ask because I had to compile up nvtop to monitor GPU usage.
> 
I kicked off a transpose and ran nvidia-smi in another window. The ffmpeg process showed up in the process list. Plus the transpose plug-in I use only works with NVEC.

> Also, when I recreate my Tdarr_node docker image (I use docker run) it basically does a chown for like an hour which I find useless because it seems to be doing chown on the database to set the owner to 1000:1000 but with 31k entries in the database from my transcoding my entire library, it takes like an hour before this process stops and the Tdarr_node is registered. Until this process finishes the Tdarr_node is not registered nor does it show up in the web interface.
> 


> ![Screenshot at 2022-08-29 07-06-18](https://user-images.githubusercontent.com/2692127/187220966-931f2360-32a4-4ad6-9d22-8cbb9e3a179b.png)
> 
> Do you experience this too?

No, but all my files were already owned by 1000:1000.  I just copied a chunk from my compose file. Thus would need to be modified to match your configuration. Your tdarr server process is likely not named Odin either.

**Comment by adefaria** [comment] 2022-08-29 17:32
> No, but all my files were already owned by 1000:1000. I just copied a chunk from my compose file. Thus would need to be modified to match your configuration. Your tdarr server process is likely not named Odin either.

Correction, the script I have that does docker run first stops the old container, removes it then uses docker run to re-create the container. I believe this causes this long-running chown to happen.

Not sure what you mean by tdarr server being named Odin...

**Comment by Lebo77** [comment] 2022-08-29 20:42
> > No, but all my files were already owned by 1000:1000. I just copied a chunk from my compose file. Thus would need to be modified to match your configuration. Your tdarr server process is likely not named Odin either.
> 
> Correction, the script I have that does docker run first stops the old container, removes it then uses docker run to re-create the container. I believe this causes this long-running chown to happen.
> 
> Not sure what you mean by tdarr server being named Odin...

The "NodeID" in my chunk of compose file above. The server I run this on is named "Odin" and it says that in the file. You will likely want to change that name. 

Also: really consider moving to docker-compose from docker run. There is a learning curve but MAN is it easier to manage once you get it working.

**Comment by adefaria** [comment] 2022-08-29 20:45
Not looking to move over to docker compose. I have a simple script. I run it once. Tdarr should then run in a container in the background with no more input from me.

There's also podman or something like that and lots of other Docker technologies. I'm not really that interested in having yet another learning curve. I have enough of them already.

**Comment by adefaria** [comment] 2022-08-31 14:20
Alas, this seemed to be working but just failed today. Note that I'm running without nvidia-docker2 installed nor used by the Docker container. I did remove it but I didn't fully remove it.

```
arth:apt list  | grep nvidia-docker

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

nvidia-docker2/bionic,now 2.11.0-1 all [residual-config]
Earth:
```
Not sure why the Docker container would use nvidia-docker2 if it's not installed but there is residual configuration so I did complete remove of nvidia-docker2 configuration and restarted the Docker container.

[IDjtt46V_-log.txt](https://github.com/HaveAGitGat/Tdarr/files/9462270/IDjtt46V_-log.txt)

**Comment by Sc0th** [comment] 2022-09-01 02:56
Since dropping `libnvidia-container-tools` down to version `1.9.0-1` I have not seen this issue reoccur, will report back if that changes.

**Comment by adefaria** [comment] 2022-09-01 17:00
As I still am seeing NO_CUDA_DEVICE I've downgraded `libnvidia-container-tools` down to version `1.9.0-1` too. Fingers crossed...

**Comment by Sc0th** [comment] 2022-09-02 01:16
[INF] infra01:~# find / -mount -type f -name nvidia-container-runtime-hook
[INF] infra01:~#

You should really consider moving away from docker, given that's dead now. cri-o & podman is painless.

**Comment by adefaria** [comment] 2022-09-02 01:33
You are definitely not a member of the KISS club!

That said I think I got you beat:
```
Earth:time docker start tdarr_node 
tdarr_node

real	0m0.390s
user	0m0.019s
sys	0m0.006s
Earth:
```

**Comment by Sc0th** [comment] 2022-09-02 01:43
Heh, I could argue that KISS is a little old school, automation for the win - I can repave my entire env (running 60 odd containers) from bare metal (tf/puppet) in just under 27 mins. If I break it, no big deal.

Also 'start' and 'restart' are different....

```
[INF] infra01:~# time podman start tdarr-node
tdarr-node

real    0m0.526s
user    0m0.037s
sys     0m0.011s
[INF] infra01:~#
```

**Comment by adefaria** [comment] 2022-09-02 02:03
While I agree, and I have taken k8s classes, etc. I just want it to work. Set and forget.

**Comment by adefaria** [comment] 2022-09-10 03:26
Any progress on this? It's a real PITA because I'm constantly restarting my Docker container by hand because I keeps getting this error.

**Comment by adefaria** [comment] 2022-09-15 14:36
Tentative solution:

I recently saw an update of libnvidia-container-tools to 1.11.0-1 and got excited that this problem might be solved. I restarted the container and it complains about GPUs. Damn! Ended up looking at my Nvidia setup and software installed. As I'm on a Thelio from System76 and they have some of their own packages so I did a complete refresh of the Nvidia stuff, basically getting system76-driver-nvidia installed and verifying that the Nvidia driver was running. Then I got the tdarr_node container up and running. It transcoded the few files in the queue using the GPUs. 

But the real test is that today I just did another transcode and it worked! Normally tdarr_node would issue this CUDA_ERROR_NO_DEVICE if it was running for more than 24 hours, but this time it succeeded!

I don't know if it was the update to libnvidia-container-tools to 1.11.0-1 or the system76-driver-nvidia refresh but I'll keep an eye on it.

**Comment by adefaria** [comment] 2022-09-15 18:00
Two new videos were also transcoded without error. I think I may be fixed but I'm not exactly sure how I fixed it.

**Comment by adefaria** [comment] 2022-09-16 04:16
I spoke too soon. The errors are back! I still have this problem.

**Comment by Sc0th** [comment] 2022-09-16 04:28
I moved to 1.11.0-1 this morning and the very next transcode failed (first in a couple of weeks) dropped back to 1.9.0-1 and all is well again.

**Comment by adefaria** [comment] 2022-09-16 18:13
Backed down to 1.9.0-1 on both libnvidia-container-tools AND nvidia-container-toolkit. I think that's the combo that will work. I'll report back.

**Comment by adefaria** [comment] 2022-09-17 03:57
Doesn't fix it. Same error! :-(

**Comment by saqebakhter** [comment] 2022-09-18 19:06
Is there any working combination of packages/drivers confirmed to work over extended time?

**Comment by adefaria** [comment] 2022-09-19 00:51
The only one claiming to have it working is @Sc0th and he uses docker-compose. I guess I'll have to check out docker-compose...

**Comment by Sc0th** [comment] 2022-09-19 01:09
podman rather than docker compose, not that it should make any difference, my node is configured thus:

```
nvidia-x11-drv-515.65.01-1.el8_6.elrepo.x86_64
nvidia-container-toolkit-1.9.0-1.x86_64
libnvidia-container1-1.11.0-1.x86_64
nvidia-x11-drv-libs-515.65.01-1.el8_6.elrepo.x86_64
libnvidia-container-tools-1.11.0-1.x86_64
kmod-nvidia-515.65.01-1.el8_6.elrepo.x86_64

podman version 4.1.1

ghcr.io/haveagitgat/tdarr_node  latest      d556192e63f7  4 months ago  1.58 GB

Mon Sep 19 09:08:27 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:00:10.0 Off |                  N/A |
|  0%   47C    P0    N/A / 120W |      0MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by Lebo77** [comment] 2022-09-19 03:13
My tdarr-node docker container has been up for 4 days now with no problems and I did a LOT of transcoding yesterday with no issues. 

Docker-compose extract:

tdarr-node:
        container_name: tdarr-node
        image: haveagitgat/tdarr_node:latest
        restart: unless-stopped
        network_mode: service:tdarr
        deploy:
          resources:
            reservations:
              devices:
                - capabilities: [gpu]
        environment:
            - TZ=America/New_York
            - PUID=1000
            - PGID=1000
            - UMASK_SET=002
            - nodeID=node1
            - nodeIP=0.0.0.0
            - nodePort=8267
            - serverIP=0.0.0.0
            - serverPort=8266
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        volumes:
            ...

Not sure WHY it started working, but I did update the docker container packages last week as part of my usual apt-get upgrade.

**Comment by Lebo77** [comment] 2022-09-29 15:51
> My tdarr-node docker container has been up for 4 days now with no problems and I did a LOT of transcoding yesterday with no issues.
> 
> Docker-compose extract:
> 
> tdarr-node: container_name: tdarr-node image: haveagitgat/tdarr_node:latest restart: unless-stopped network_mode: service:tdarr deploy: resources: reservations: devices: - capabilities: [gpu] environment: - TZ=America/New_York - PUID=1000 - PGID=1000 - UMASK_SET=002 - nodeID=node1 - nodeIP=0.0.0.0 - nodePort=8267 - serverIP=0.0.0.0 - serverPort=8266 - NVIDIA_VISIBLE_DEVICES=all - NVIDIA_DRIVER_CAPABILITIES=all volumes: ...
> 
> Not sure WHY it started working, but I did update the docker container packages last week as part of my usual apt-get upgrade.

Ignore this. Not working again.

**Comment by adefaria** [comment] 2022-10-06 03:54
How exactly do you set `systemd.unified_cgroup_heirachy=0`? I've researched a bit and I think I'm merely supposed to set
```
GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
```
Run `update-grub` then reboot. But I want to be sure since this is modifying the boot and I don't want to get locked out. 

BTW what I at https://askubuntu.com/questions/1389602/how-to-set-cgroup-memory-enable-on-ubuntu-21-10 found said:
> A note to anyone enabling cgroups for AWS Greengrass: Edit GRUB_CMDLINE_LINUX to be:
>
> ```
> GRUB_CMDLINE_LINUX="cgroup_enable=memory cgroup_memory=1 systemd.unified_cgroup_hierarchy=0"
> ```
And I'm also not sure if I should include the `cgroup_enable=memory cgroup_memory=1` portion.

**Comment by tedcook94** [comment] 2022-10-06 04:06
Assuming you're using Ubuntu, [here is the relevant documentation](https://wiki.ubuntu.com/Kernel/KernelBootParameters) on setting a kernel parameter. It discusses how to set a temporary parameter, which you could do first as a test if you're concerned about problems booting. If that goes well, you can then follow the instructions for permanently setting it.

As for those other parameters you mentioned, I didn't set those. It seems like that other post is talking about configuring a server for [AWS's Greengrass service](https://aws.amazon.com/greengrass/), which doesn't seem relevant to Tdarr in any way.

**Comment by Lebo77** [comment] 2022-10-06 14:06
Well, I just added the recommended parameter to grub and rebooted. We will see if that fixes it.

**Comment by adefaria** [comment] 2022-10-06 14:09
Hmmm... `Still` having found how to get to the GRUB menu on my System76 Thelio but I figured I'd simply try to update-grub with the change put into /etc/defaults/grub. I rebooted and went through a few transcodes that queued up without a problem. That was yesterday. Today a new download came in and it transcoded with success! First time I had my Tdarr node survive and overnight! Look like this may be the fix.

Of course, I wonder if Nvidia will fix this and use the newer cgroup hierarchy and how I might be notified so I can remove this setting and start using the newer setting.

**Comment by tedcook94** [comment] 2022-10-06 14:50
I'm not sure if this is a Nvidia or a Tdarr issue. I have two other Docker containers (`plex` and `foldingathome`) that both use the same GPU as my Tdarr container, and they never had any issues before or after I added the kernel parameter. Only Tdarr would "lose" the GPU from time to time.

I'm no expert on cgroups, but [it looks like there were some deprecated features when going from v1 to v2](https://docs.kernel.org/admin-guide/cgroup-v2.html#deprecated-v1-core-features). Maybe Tdarr is either directly or indirectly using some deprecated v1 feature?

**Comment by adefaria** [comment] 2022-10-06 14:53
Inntereing observation! I didn't think about it but yes, my Plex also runs in a Docker container and uses the CPUs for hardware transcoding. This sounds like good info for the developer.

**Comment by adefaria** [comment] 2022-10-07 03:54
Well for me it's working. What OS/distro are you on? If you didn't type in the right stuff, didn't run update-grub or didn't reboot the Linux kernel will not warn you that you got it wrong.

I'm on Ubuntu 22.04 and I have the following in `/etc/defautls/grub`
```
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash systemd.unified_cgroup_hierarchy=0"
```
I've run `update-grub` and rebooted. My Tdarr node has stayed up for about 2 days, much longer than ever before without complaining about this error, and has been transcoding videos. In fact, it just transcoded 4 videos.

**Comment by Lebo77** [comment] 2022-10-12 16:06
The grub parameter change seems to be working for me. I am on Ubuntu 22.04.1 LTS. 

This is an OK workaround, but hopefully this can get fixed so that users are not required to change how the kernel is operating just to make this work.

**Comment by tedcook94** [comment] 2022-10-12 16:14
+1 for this being a workaround, but not an actual fix. However, since we have at least 3 people here who this seemed to resolve their issue, I'm sure there are others that have had similar issues and didn't find this solution.

@HaveAGitGat, could we possibly document this workaround somewhere in the README/on docs.tdarr.io until a better or more permanent solution is found?

**Comment by yajrendrag** [comment] 2022-12-31 06:15
I'd been having the same issues - tdarr would work fine for about a day, and then I'd have to restart the containers in order for transcodes to ocurr.  When i finally chased it down, I was getting the same error as OP and found a solution on the Arch wiki - though i am running Ubuntu 22.04 and docker 20.10.22.  Seems to be an nvidia / docker issue.  see Howard O-Neil's reply [here](https://bbs.archlinux.org/viewtopic.php?pid=1976296#p1976296).  About half way through his answer he gives an alternative method.

There he details two ways to make this work that don't require adding kernel parameters:

(1) set the container to privileged.  After doing this, i never got the "CUDA_ERROR_NO_DEVICE" error and transcoding continues to work just fine without requiring container restarts.
(2) Alternatively, if you don't wish to run the container with elevated privileges, you can change the way you do gpu passthrough to use nvidia-container-runtime.  nvidia-container-toolkit on ubuntu now contains nvidia-container-runtime, so nothing to install and `/etc/docker/daemon.json` exists and doesn't require changes.  You just need to change the docker run: change `--gpus=all` to `--runtime nvidia` and then explicitly add all the /dev/nvidia devices: 

```
   --device=/dev/nvidia-caps:/dev/nvidia-caps \
   --device=/dev/nvidia0:/dev/nvidia0 \
   --device=/dev/nvidiactl:/dev/nvidiactl \
   --device=/dev/nvidia-modeset:/dev/nvidia-modeset \
   --device=/dev/nvidia-uvm:/dev/nvidia-uvm \
   --device=/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools \
```

Similarly, you can change the compose file to effect these same changes / additions.

Running the containers this way has also resulted in no "CUDA_ERROR_NO_DEVICE" errors and transcoding works without requiring daily-ish restarts.

**Comment by HaveAGitGat** [comment] 2023-02-07 05:52
@tedcook94 added to the troubleshooting section: 
https://docs.tdarr.io/docs/troubleshooting/#cuda_error_no_device-no-cuda-capable-device

**Comment by HaveAGitGat** [comment] 2023-03-17 08:23
Issue is open on Jellyfin here so will let solution be handled there ty: https://github.com/jellyfin/jellyfin/issues/9287

**Closed by HaveAGitGat** 2023-03-17 08:23 UTC
Labels: bug

**Comment by tharun571** [comment] 2026-01-20 18:39
Docker GPU detection can be especially tricky - nvidia-smi working on the host doesn't guarantee container access.

Key Docker GPU troubleshooting steps:
- Verify `nvidia-container-runtime` is installed and configured
- Check Docker daemon config includes nvidia runtime
- Ensure container has proper `--runtime=nvidia` or `--gpus all` flags
- Validate CUDA libraries are accessible inside container

I built **[env-doctor](https://github.com/mitulgarg/env-doctor)** specifically to help diagnose these Docker+GPU issues. It checks:
- Docker runtime configuration
- GPU forwarding to containers
- CUDA library paths and permissions
- Works both inside/outside Docker to pinpoint where detection fails

Full disclosure: I'm the author. Sharing because Docker GPU setup has unique challenges vs host GPU detection. Hope it helps others troubleshoot these issues!
