### ISSUE TITLE
Disappearing from Transcode Sucess Tab

### ISSUE THREAD

**Issue by jleck** [HaveAGitGat/Tdarr#198] opened 2020-04-08 18:34 UTC
**Describe the bug**
Files disappearing from transcode success/not required.

**Expected behavior**
Transcoded file, once complete it moved to transcode success/not required. It disappears a couple minutes later. It then shows up queue again, and moves straight to success/not required when processed.

Not the worst bug in itself, but I order by queue by largest usually, so it doesn't get picked up for a while.

**Desktop (please complete the following information):**
 - Unraid

**Additional context**
I am running 10 transcodes (nvenc) + 2 health checks, cpu is maxed out. Not sure if that has some impact.

**Comment by HaveAGitGat** [comment] 2020-04-09 19:14
This is to do with the fix for the following bug:

>New files are not detected when replacing a file with the exact same name+extension. 
For example when a 3rd party program upgrades a file to a higher quality. 

Now the issue is, the new files Tdarr produces are being scanned twice - a forced scan after the transcode, and then the folder watcher scans the file again a few seconds/mins later (depending on the scan interval) which causes it to go back into the transcode queue again.

Will go about fixing it 👍

**Comment by mattispantone81** [comment] 2020-04-18 10:39
To confirm I am also having this issue. Let me know if you need any logs or data.

**Comment by HaveAGitGat** [comment] 2020-04-18 15:09
@jleck @mattispantone81 should now be fixed as of 1.108

**Closed by HaveAGitGat** 2020-04-18 15:09 UTC

**Comment by mattispantone81** [comment] 2020-04-18 20:05
Has 1.108 been release yet?

According to Tdarr I am running the latest version and there are no available updates in Unraid 6.8.1. 




Regards,


Mat Fehlandt

**Comment by HaveAGitGat** [comment] 2020-04-18 20:17
Yes the updates were pushed to Docker 5 hours ago.

https://hub.docker.com/layers/haveagitgat/tdarr/latest/images/sha256-178f9d0947b9bd3ec2a63dfeb0cc742cd2e5fcea6d39b9e704e51ba97452e4a2?context=explore

https://hub.docker.com/layers/haveagitgat/tdarr_aio/latest/images/sha256-79c546766c26f8c5b336de8cd2e52252ad45767ed52c533a369ed6b82e858bdc?context=explore

**Comment by mattispantone81** [comment] 2020-04-18 20:18
Ok so that’s weird. I just did a force update on the docker and Tdarr is now showing 1.08. 

Will confirm if that solves the issue. Thank you for your support. 

This is a great docker that’s saving me a lot of space on my array. Over 1.3TB so far. Can’t wait to see what’s next. 

Regards,


Mat Fehlandt

**Comment by mattispantone81** [comment] 2020-04-18 20:19
Ah. That makes sense now. Can’t thank you enough. 😊



Regards,


Mat Fehlandt
