### ISSUE TITLE
RAM usage Problem?

### ISSUE THREAD

**Issue by RangerFX4** [HaveAGitGat/Tdarr#374] opened 2021-02-22 01:19 UTC
Hi,

I am encountering a certain problem. I have to turn off the tdarr_node after few hours of GPU encoding to reset the ram usage of Tdarr v2.

**Describe the bug**
I observed that recently after updating to V2 ram is increasing every finished encoded video.

**To Reproduce**
Start GPU encoding using one worker.

Library Plug-ins:
Tdarr_Plugin_lmg1_Reorder_Streams
Tdarr_Plugin_MC93_Migz2CleanTitle
Tdarr_Plugin_MC93_MigzImageRemoval
Tdarr_Plugin_MC93_Migz5ConvertAudio
Tdarr_Plugin_vdka_Tiered_NVENC_CQV_BASED_CONFIGURABLE

tdarr_node:

Allow GPU workers to do CPU tasks: **ON** 
Always move failed transcodes to Transcode Error tab: **ON**

**Expected behavior**
Using 1050ti GPU after encoding ram usage increase slightly.

**Desktop (please complete the following information):**
 - OS:  **Unraid 6.9.0-rc2**
 - Browser: **Egde**
 - Version: **Docker Tdarr 2.00.05**

Regards!

**Comment by caiusseverus** [comment] 2021-02-22 03:22
I think this is to do with health checks using the basic check. I find that if many files are checked, the threads that are spawned for each one don’t despawn and gradually use up all available ram. I had to set a memory limit on the node container so it gets restarted, otherwise it ground the whole machine to a halt.

**Comment by RangerFX4** [comment] 2021-02-22 07:52
For me putting the parameter --memory=8G for Tdarr server and node does not work cause I the node will not comeback after reaching 8GB limit. I have to manually restart the docker.

**Comment by HaveAGitGat** [comment] 2021-02-22 11:46
This is fixed in 2.00.06 which you can now use. I'll put into 'latest' later today.

**Closed by HaveAGitGat** 2021-02-22 11:46 UTC

**Comment by vontrapp** [comment] 2021-09-30 02:07
Did this have a regression? I'm having what seems to be the same issue. Version 2.00.10

**Comment by salcio** [comment] 2021-10-04 09:41
I've got the same issue - Version 2.00.10. Can we reopen this one ?

**Comment by jacauc** [comment] 2021-10-06 18:26
Confirmed regression on 2.00.10

**Comment by mbentley** [comment] 2022-02-06 11:53
I am running 2.00.13 and just had the same issue with memory usage spiking with my one worker which has a GPU:

<img width="1599" alt="screenshot 2022-02-06 at 6 28 04 AM" src="https://user-images.githubusercontent.com/414445/152678725-16e70c7a-b4f6-4ed7-9735-09a04685624d.png">

Logs from my container:

```
<--- Last few GCs --->
= [38463:0x2ff5340]  4883384 ms: Mark-sweep (reduce) 4095.3 (4101.4) -> 4094.4 (4102.4) MB, 2611.5 / 0.0 ms  (+ 1.0 ms in 3782 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 2641 ms) (average mu = 0.182, current mu = 0.01[38463:0x2ff5340]  4884756 ms: Mark-sweep (reduce) 4094.7 (4101.4) -> 4094.5 (4102.4) MB, 1339.5 / 0.0 ms  (+ 29.3 ms in 31 steps since start of marking, biggest step 15.6 ms, walltime since start of marking 1372 ms) (average mu = 0.124, current mu = 0.00

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
 1: 0x8de370 node::Abort() [/app/Tdarr_Node/Tdarr_Node]
 2: 0x82772b node::FatalError(char const*, char const*) [/app/Tdarr_Node/Tdarr_Node]
 3: 0x9f2a76 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/app/Tdarr_Node/Tdarr_Node]
 4: 0x9f2d0d v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/app/Tdarr_Node/Tdarr_Node]
 5: 0xb95135  [/app/Tdarr_Node/Tdarr_Node]
 6: 0xbb4d3e  [/app/Tdarr_Node/Tdarr_Node]
 7: 0xbd17c7 v8::internal::FullEvacuator::RawEvacuatePage(v8::internal::MemoryChunk*, long*) [/app/Tdarr_Node/Tdarr_Node]
 8: 0xbcc05a v8::internal::Evacuator::EvacuatePage(v8::internal::MemoryChunk*) [/app/Tdarr_Node/Tdarr_Node]
 9: 0xbd1f08  [/app/Tdarr_Node/Tdarr_Node]
10: 0xbb1b89 v8::internal::ItemParallelJob::Run() [/app/Tdarr_Node/Tdarr_Node]
11: 0xbd3183 v8::internal::MarkCompactCollector::EvacuatePagesInParallel() [/app/Tdarr_Node/Tdarr_Node]
12: 0xbd3a26 v8::internal::MarkCompactCollector::Evacuate() [/app/Tdarr_Node/Tdarr_Node]
13: 0xbb61f9 v8::internal::MarkCompactCollector::CollectGarbage() [/app/Tdarr_Node/Tdarr_Node]
14: 0xb9d8dc v8::internal::Heap::MarkCompact() [/app/Tdarr_Node/Tdarr_Node]
15: 0xb9eb28 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/app/Tdarr_Node/Tdarr_Node]
16: 0xba1d30 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/app/Tdarr_Node/Tdarr_Node]
17: 0xc01258 v8::internal::ScavengeJob::Task::RunInternal() [/app/Tdarr_Node/Tdarr_Node]
18: 0x95320e node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [/app/Tdarr_Node/Tdarr_Node]
19: 0x9535d0 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/app/Tdarr_Node/Tdarr_Node]
20: 0x1121e75  [/app/Tdarr_Node/Tdarr_Node]
21: 0x11375cf  [/app/Tdarr_Node/Tdarr_Node]
22: 0x1684538  [/app/Tdarr_Node/Tdarr_Node]
23: 0x932df7 node::NodeMainInstance::Run() [/app/Tdarr_Node/Tdarr_Node]
24: 0x8bcfa3 node::Start(int, char**) [/app/Tdarr_Node/Tdarr_Node]
25: 0x7f96741350b3 __libc_start_main [/usr/lib/x86_64-linux-gnu/libc.so.6]
26: 0x840a51  [/app/Tdarr_Node/Tdarr_Node]
```

I'm running with a fairly conservative amount of RAM allocated to my Docker container - 6GB:

```
docker run -itd \
  --name tdarr-node1 \
  --network load-balancer \
  --ip 172.20.0.37 \
  --restart unless-stopped \
  --cpus 4 \
  --memory 6G \
  --memory-swap 7G \
  --mount type=bind,source=/zfs/apps/tdarr/configs,destination=/app/configs,readonly=false \
  --mount type=bind,source=/zfs/apps/tdarr/logs,destination=/app/logs,readonly=false \
  --mount type=bind,source=/zfs/storage/media,destination=/media,readonly=false \
  --mount type=bind,source=/zfs/apps/tdarr/transcode_cache,destination=/temp,readonly=false \
  -e nodeID="node1" \
  -e nodeIP="172.20.0.37" \
  -e nodePort="8267" \
  -e serverIP="172.20.0.36" \
  -e serverPort="8266" \
  -e TZ="US/Eastern" \
  -e PUID=501 \
  -e PGID=1501 \
  -e NVIDIA_DRIVER_CAPABILITIES="all" \
  -e NVIDIA_VISIBLE_DEVICES="all" \
  --runtime=nvidia \
  --gpus=all \
  haveagitgat/tdarr_node
```

It was looking like a reasonable amount of RAM to allocate based off of usage over the past 24 hours while transcoding:

<img width="1601" alt="screenshot 2022-02-06 at 6 45 55 AM" src="https://user-images.githubusercontent.com/414445/152679353-d39cd81e-06bb-44cf-8b81-62e87badf5a2.png">

Of course, that would be unless there is some process that kicks off that would require a larger amount of RAM for a short period of time which is always possible.

**Comment by mbentley** [comment] 2022-02-08 14:48
I just had this happen again even after increasing the container memory available to make sure I wasn't hitting any issues with the memory limit.  It was toward the end of processing a transcode; it was showing 99.68% complete and my GPU (Quadro P2000) returned to idle but the `ffmpeg` process was still running with a decent amount of CPU usage while memory usage was increasing on the container and finally spiked at 56% of the container limit:

![screenshot 2022-02-08 at 9 41 05 AM](https://user-images.githubusercontent.com/414445/153010365-f3291eca-5419-4877-89f4-aea6be3b4bb2.png)

Unfortunately I wasn't paying attention to the memory usage by process so I am not sure if there was increasing memory utilization by `ffmpeg` or the `Tdarr_Node` process but I would assume it was Tdarr_Node based on the logs again:

```
<--- Last few GCs --->

[71153:0x2e1c340]  1672191 ms: Mark-sweep (reduce) 4093.7 (4103.1) -> 4093.5 (4103.6) MB, 121.1 / 0.0 ms  (+ 1355.7 ms in 188 steps since start of marking, biggest step 39.1 ms, walltime since start of marking 1594 ms) (average mu = 0.343, current mu = 0.[71153:0x2e1c340]  1673889 ms: Mark-sweep 4094.5 (4100.6) -> 4093.7 (4102.1) MB, 1644.6 / 0.0 ms  (average mu = 0.211, current mu = 0.031) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8de370 node::Abort() [/app/Tdarr_Node/Tdarr_Node]
 2: 0x82772b node::FatalError(char const*, char const*) [/app/Tdarr_Node/Tdarr_Node]
 3: 0x9f2a76 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/app/Tdarr_Node/Tdarr_Node]
 4: 0x9f2d0d v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/app/Tdarr_Node/Tdarr_Node]
 5: 0xb95135  [/app/Tdarr_Node/Tdarr_Node]
 6: 0xb95b87 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/app/Tdarr_Node/Tdarr_Node]
 7: 0xb9e708 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/app/Tdarr_Node/Tdarr_Node]
 8: 0xba1d30 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/app/Tdarr_Node/Tdarr_Node]
 9: 0x16b17fd  [/app/Tdarr_Node/Tdarr_Node]
10: 0xb65cb3 v8::internal::FactoryBase<v8::internal::Factory>::NewRawOneByteString(int, v8::internal::AllocationType) [/app/Tdarr_Node/Tdarr_Node]
11: 0xb71f0d v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const> const&, v8::internal::AllocationType) [/app/Tdarr_Node/Tdarr_Node]
12: 0x1684d15  [/app/Tdarr_Node/Tdarr_Node]
13: 0x9a88e9  [/app/Tdarr_Node/Tdarr_Node]
14: 0x8c560a  [/app/Tdarr_Node/Tdarr_Node]
15: 0x1700dad  [/app/Tdarr_Node/Tdarr_Node]
```

**Comment by mbentley** [comment] 2022-02-08 15:17
So I figured out what is going on.  One thing I noticed was that `ffmpeg` continues to run afterward disconnect.  I decided to manually run a transcode to see what might be happening and the problem is with the source file it seems.

The logs from `ffmpeg` steam these lines repeating:

```
[h264_cuvid @ 0x5630cbde1e80] cuvid decode callback error
Error while decoding stream #0:0: Generic error in an external library
```

And the process just stays hung.  I wonder if it could be possible to detect these sorts of errors in some way to do some safeguarding.  It's just a guess but it might be that the memory utilization is from the `ffmpeg` logs.  I'd be happy to share the source video file privately if it would be helpful (it's about 5 GB).

**Comment by ghzgod** [comment] 2022-07-19 17:34
> So I figured out what is going on. One thing I noticed was that `ffmpeg` continues to run afterward disconnect. I decided to manually run a transcode to see what might be happening and the problem is with the source file it seems.
> 
> The logs from `ffmpeg` steam these lines repeating:
> 
> ```
> [h264_cuvid @ 0x5630cbde1e80] cuvid decode callback error
> Error while decoding stream #0:0: Generic error in an external library
> ```
> 
> And the process just stays hung. I wonder if it could be possible to detect these sorts of errors in some way to do some safeguarding. It's just a guess but it might be that the memory utilization is from the `ffmpeg` logs. I'd be happy to share the source video file privately if it would be helpful (it's about 5 GB).

Have you figured out a automatic work around?

**Comment by mbentley** [comment] 2022-07-19 18:05
Automatic, no.  Only thing I could think of that might be able to help might be a healthcheck script that somehow could determine if a `ffmpeg` process is running for an extended period of time, longer than expected but I am not sure there is a good hook or method to be able to match an error to a process that no longer has a job attached.  I've basically just given up on that and utilize monitoring to see if there are files that are triggering the high memory usage scenario as it had only happened with a single file for me.
