### ISSUE TITLE
Rename transcoded files

### ISSUE THREAD

**Issue by Xe138** [HaveAGitGat/Tdarr#1] opened 2019-09-25 18:24 UTC
Would it be possible to have some more control over how transcoded files are handled?  I tag the codec of the file in filenames, which becomes incorrect after tdarr transcodes them.

Potential solutions:
- transcoded files can be directed to an alternate directory to be manually imported or handled by another application.
- transcoded files can be automatically imported by radarr/sonarr, and thus renamed and the file history tracked.
or
- transcoded files are automatically renamed by tdarr

**Comment by HaveAGitGat** [comment] 2019-09-25 18:33
@Xe138 absolutely, I’m looking to integrate with Sonarr/Radarr. Just getting the core functionality working first :).

I will put out an update later which will hopefully provide more functionality.

**Comment by HaveAGitGat** [comment] 2019-09-25 22:36
@Xe138 I have pushed a new docker update (if that's what you're using).

You can now use plugins to provide more flexibility on how you transcode your files. If you know a bit of javascript/nodejs you can write your own plugins and add them to the community plugins. There are a few already.

**Comment by Xe138** [comment] 2019-09-26 13:12
@HaveAGitGat thanks!  I'll take a look at writing some plugins soon.

Thanks for the great application!  Tdarr is already replacing my previous encoding pipeline.

**Comment by Xe138** [comment] 2019-11-22 17:09
With the "Output Folder" feature, this issue has been addressed.  With the most recent update, all files are sent to the output folder, even if they are not altered.  I understand that this would be useful in some workflows (e.g. processing new media before adding it to the library), but there should be an option to disable this.

In my use case, I have tdarr running to convert media that exists in my library.  I do not want it to immediately replace the original files because I update the file names to show the encoding.  I have tdarr output to a folder that I can then import to my library using other software that will maintain the desired naming structure.  The current solution works, but spends a lot of time copying files that don't actually need to be copied.

I suggest an additional toggle in the "Output Folder" section of the library tab for "Skip unaltered files" or "Copy unaltered files".

**Comment by HaveAGitGat** [comment] 2019-11-24 19:55
Ok I’ll add that in

**Comment by HaveAGitGat** [comment] 2019-11-25 18:45
@Xe138  I've added the option to disable copy in 1.0071

**Comment by Xe138** [comment] 2019-11-25 19:25
@HaveAGitGat 
Works great.  Thanks!

**Comment by azcom** [comment] 2019-11-28 00:07
Thank you! I was about to request this myself (a toggle to put only the transcoded files into output directory) when I found you've just added it. Perfect! My workflow appears the same as that of @Xe138

The only issue I have with this now is that the files are always saved in the output directory with their original directory tree so after manually importing with Sonarr/Radarr I'm having to find and delete empty folders. Not quite as automated as i'm aiming for. A simple toggle to choose to keep the source directory structure or just save files without any and go directly to the output folder would be perfect. Obviously the ability to trigger an import via api/direct Sonarr/Radarr integration is now top of my wishlist but until then the ability to output just files without directories will keep me happy for now. A periodic manual import while not quite automatic won't hurt for now. You can't make it perfect overnight and I appreciate all you've done with this so far.

Thanks so much for your hard work on this. This project is something I've been wanting in my toolkit for so so long. The final piece of the puzzle if you will. I'm so glad you decided to do this and I can't wait to watch it mature and just get better & better.

**Comment by azcom** [comment] 2019-11-28 15:32
@HaveAGitGat
One other thing I've noticed since.......

When using a specific output folder and closely monitoring the behaviour of Tdarr I have noticed files being transcoded multiple times, sometimes at the same time (if I have more workers active). Until I manually import with Sonarr and it picks up on the codec change and then no longer transcodes as it doesn't match my plugin stack rules. Thinking logically this would be expected behaviour **IF** Tdarr wasn't aware that a particular file was currently being processed and thus in the cache folder or has a previously completed transcoded file sat in the output folder. I'm not sure what checks you have in place to make Tdarr aware of what is being dealt with or has been dealt with already but it appears not present or not working for me with my workflow. Looking again now there are actually a couple of other bugs I have identified too but I don't want to bombard you with them all at once!

**Comment by azcom** [comment] 2019-12-01 08:28
> @HaveAGitGat
> One other thing I've noticed since.......
> 
> When using a specific output folder and closely monitoring the behaviour of Tdarr I have noticed files being transcoded multiple times, sometimes at the same time (if I have more workers active). Until I manually import with Sonarr and it picks up on the codec change and then no longer transcodes as it doesn't match my plugin stack rules. Thinking logically this would be expected behaviour **IF** Tdarr wasn't aware that a particular file was currently being processed and thus in the cache folder or has a previously completed transcoded file sat in the output folder. I'm not sure what checks you have in place to make Tdarr aware of what is being dealt with or has been dealt with already but it appears not present or not working for me with my workflow. Looking again now there are actually a couple of other bugs I have identified too but I don't want to bombard you with them all at once!

It would appear after some playing with things to try and figure out this multiple transcoding of the same file issue that after adding a trailing forward slash in the 3 path fields for all the libraries that it stops some additional strange behaviour I didn't previously mention and also this issue too. I had to do this directly in the database with compass in the end as it didn't always seem to take hold in the Tdarr web app. I think because much of the time it's not updating info in or out of it and won't at these times won't even reload the page , depending on what the  cmd box is showing is being performed (anonother bug?). Shouldn't the front end respond regardless of whatever the back end is doing?

**Comment by HaveAGitGat** [comment] 2019-12-01 13:57
@azcom thanks but it would be best to open new, concise issues/requests rather than stacking blocks of text on an unrelated old issue as it makes it difficult to manage if that's okay :)

**Comment by HaveAGitGat** [comment] 2019-12-01 16:06
>When using a specific output folder and closely monitoring the behaviour of Tdarr I have noticed files being transcoded multiple times

Just to double check, you understand that files are processed multiple times if you have multiple plugins right? As is mentioned in Tdarr:

> For example, without plugins, the transcode process will be:
> 
> Source ---> Cache ---> Output
> 
> With plugins:
> 
> Plugin 1: Source ---> Cache ---> Output
> 
> Plugin 2: Output ---> Cache ---> Output
> 
> Plugin 3: Output ---> Cache ---> Output
> 
> etc

**Comment by HaveAGitGat** [comment] 2019-12-01 23:12
@azcom  

>When using a specific output folder and closely monitoring the behaviour of Tdarr I have noticed files being transcoded multiple times

This should be fixed in 1.008 just released. Perhap some of the other issues are also resolved for you.

**Comment by azcom** [comment] 2019-12-11 12:36
> @azcom thanks but it would be best to open new, concise issues/requests rather than stacking blocks of text on an unrelated old issue as it makes it difficult to manage if that's okay :)

My apologies. I think I just got a bit carried away once I started typing. I only set out with a 'Thank You' in mind.

**Comment by HaveAGitGat** [comment] 2020-02-03 05:13
Current output folder method will be scrapped.

Post processing plugins will be used instead to achieve this, with customisable variables:
https://github.com/HaveAGitGat/Tdarr/issues/136

With these you'll be able to:
Move, rename, delete files
Update Tdarr database
Interface with Sonarr/Plex/Radarr
Keep source directory structure or not
Etc

This will prevent the problem of the output folder not having fully completed files in and make things simpler for Tdarr Cluster.

**Comment by HaveAGitGat** [comment] 2020-02-08 09:01
There is now a basic plugin to rename files. Make sure you’re on Tdarr 1.104

Tdarr_Plugin_z18s_rename_files_based_on_codec

This plugin renames 264 files to 265 or vice versa depending on codec. 

It only renames files if they have hevc,265, or 264 in the file name.

**Comment by HaveAGitGat** [comment] 2020-02-18 08:29
Closing this as the original requests have been dealt with and there's a separate issue for the latter problems.

**Closed by HaveAGitGat** 2020-02-18 08:29 UTC
Labels: enhancement
