### ISSUE TITLE
Copy file to specific location before transcoding 

### ISSUE THREAD

**Issue by svb91** [HaveAGitGat/Tdarr#709] opened 2022-12-10 16:58 UTC
I know that this was already a request 2 years ago (see #286) but I have a specific need for which I want to transfer the file before the transcoding starts.

I'm running a Unraid server with multiple HDDs and I want to reduce the space needed for my collection. To convert all my files it will take several weeks in which at least one HDD will always on and uses power. 
If I could copy the entire folder to my cache drive first, I could save some energy while processing my entire collection.

Right now I do it manually, but I think that there should be a plugin for that which does a copy first.

**Comment by HaveAGitGat** [comment] 2023-02-22 20:28
Duplicate of https://github.com/HaveAGitGat/Tdarr/issues/709 so will handle there

**Closed by HaveAGitGat** 2023-02-22 20:28 UTC
Labels: enhancement

**Comment by HaveAGitGat** [comment] 2024-10-19 00:36
2.27.01 just released adds a new node type 'unmapped' nodes, more info here: https://docs.tdarr.io/docs/nodes/nodes#unmapped
