### ISSUE TITLE
Problem with detection of gpu node type and job assignment.

### ISSUE THREAD

**Issue by caiusseverus** [HaveAGitGat/Tdarr#343] opened 2021-02-02 04:16 UTC
I have two two nodes set up. One is running on the same linux machine as the server, and uses vaapi for transcoding. The other is on my windows desktop which has an nvidia card, for when it's not being used for other things. 

I have the following plugin stack:
Community,Tdarr_Plugin_lmg1_Reorder_Streams,
Community,Tdarr_Plugin_MC93_Migz1Remux,
Community,Tdarr_Plugin_Mthr_VaapiHEVCTranscode,
Community,Tdarr_Plugin_MC93_Migz1FFMPEG,   (this one is nvenc enabled)
Community,Tdarr_Plugin_MC93_Migz3CleanAudio,
Community,Tdarr_Plugin_MC93_Migz5ConvertAudio
,Community,Tdarr_Plugin_MC93_Migz4CleanSubs

Both nodes have the appropriate hardware encoding type set, and are enabled to allow GPU workers to do CPU tasks.

If I have both nodes active, the GPU workers pull files from the queue and start transcoding them as expected, however the transcoded files are added to the staging section and sit with the status 'require CPU worker'. When one of the workers finishes transcoding, instead of picking up one of these files, it pulls a new one from the queue. This results in a growing list of files in the staging area. Some of these are partially processed, and have generated a file in the tdarr cache folder while others which did not need transcoding as they were already hevc are just listed there waiting for a CPU worker to do the audio/subtitles.

The obvious solution might appear to be to enable a CPU worker on the linux node that's always available, and this does work at first to clear the list. There is then a problem that if the nvidia node gets switched off, the CPU worker on the linux node starts trying to process files from the queue using the nvenc plugin, which causes them to fail and get added to the transcode error list.

I think there are two problems here - first the GPU workers are not always prioritising jobs from the staging area before the queue, necessitating having a CPU worker available which leads to:

Secondly, when there is a hardware specific plugin in the stack, it's not being ignored by CPU workers on nodes that don't have that hardware if that particular node is not available, leading to transcoding failures.

**Comment by caiusseverus** [comment] 2021-02-04 00:02
A bit more information after further experiments. 

First test:
I completely disabled the second node and disabled the relevant plugin from the stack for testing. Everything is now on one machine with vaapi.

I have rearranged the stack to put the transcoding plugin last. With a single gpu worker enabled (with cpu tasks enabled), it appears to function as expected, with files being processed properly and copied back to the media location after all plugins have finished.

If I enable an additional CPU worker alongside the GPU worker, then files are taken from the queue and processed until they get to the transcoding stage where they stop with the status of 'require GPU worker'. This is as expected, since GPU transcodes take longer than the CPU tasks.

The GPU worker finished its current task and then picked up the next one from the staging section which was then completed OK and copied back to replace the original file.

Second test:
vaapi node workers all disabled, nvidia node enabled with one gpu worker with cpu tasks enabled.
NVENC plugin is run last in the stack, vaapi plugin disabled.

In this case, files are picked up from the queue and processed through the cpu plugins. The final nvenc plugin is run and completed, but instead of copying the file back to the original drive, it is added to the staging area saying 'require CPU worker'. There are no further plugins to be run however, and the GPU worker picks up a new file from the queue and starts processing it.

Enabling a CPU worker, these staged files are picked up and processed, but not correctly. The CPU worker doesn't actually do anything with them, it just clears the list and the files appear under the 'Transcode success' list, despite them not being copied back to the original drive. They are still shown as h264 files in the list, and the original files on the media drive are still in place.

This does not seem to be specific to the nvenc plugin I listed above. I tried it with a different one, and it still results in files getting stuck in the staging area.

Third test:
Both nodes enabled with 1 gpu worker. 

Both gpu workers pick a file up from the queue and process the cpu plugins. The vaapi node successfully transcodes the file and copies it back to the media drive. The nvenc node however transcodes the file and once again leaves it in the staging area without copying it back. The vaapi node ignores this staged file and picks up a new file from the queue, which it successfully processes completely.

This leads me to conclude that it is the nvidia node that is causing the errors. I don't know if it is the node itself, how the server is handling it, or if it's specific to the windows version of the node. The vaapi node appears to run correctly.

The nvidia node is running on a windows 10 machine with a 1060 card, and a native install (no docker) of tdarr v2.00.03.

**Comment by HaveAGitGat** [comment] 2021-02-07 09:09
This should be fixed in today’s update. Had to move quite a few things around but I think it’s working nicely now. The staging section now also shows the exact hardware needed once the task is evaluated. For example, if a QSV node picks up the task and it turns out to be an NVENC task, it will be placed back in the staging section where it will show ‘Requires NVENC Worker’.

**Comment by HaveAGitGat** [comment] 2021-02-07 13:01
2.00.04 is now in pre-release so you have to manually specify 2.00.04 in the Tdarr_Updater config (or specify the Docker tag)

```
{
  "platform_arch": "default",
  "modules": {
    "Tdarr_Desktop": {
      "enabled": true,
      "requiredVersion": "2.00.04",
      "currentVersion": ""
    },
    "Tdarr_Node": {
      "enabled": true,
      "requiredVersion": "2.00.04",
      "currentVersion": ""
    },
    "Tdarr_Server": {
      "enabled": true,
      "requiredVersion": "2.00.04",
      "currentVersion": ""
    },
    "Tdarr_WebUI": {
      "enabled": true,
      "requiredVersion": "2.00.04",
      "currentVersion": ""
    }
  }
}
```

Let me know if it fixes the issue :). Thanks

**Comment by caiusseverus** [comment] 2021-02-08 03:36
I've updated to 2.00.04 and done some more testing. There are still some problems which I've detailed below. I've been able to consistently reproduce these.

The plugin stack is:

1. Community,Tdarr_Plugin_MC93_Migz6OrderStreams
2. Community,Tdarr_Plugin_MC93_MigzImageRemoval
3. Community,Tdarr_Plugin_MC93_Migz1Remux
4. Community,Tdarr_Plugin_MC93_Migz4CleanSubs
5. Community,Tdarr_Plugin_MC93_Migz3CleanAudio
6. Community,Tdarr_Plugin_MC93_Migz5ConvertAudi,
7. Community,Tdarr_Plugin_MC93_Migz1FFMPEG
8. Community,Tdarr_Plugin_Mthr_VaapiHEVCTranscode

For a test library I'm just using these h264 THX trailers, as they aren't too big and allow repeatability: https://thedigitaltheater.com/thx-trailers/

**First case:** 
Both nodes have 1 GPU worker each with CPU tasks enabled. Plugin stack as above.

Files process through the first 6 CPU plugins OK. Output is generated in the cache folder. 

Files which are allocated to the nvenc node 7 are processed with plugin 7 and the transcoded file is generated in the cache. On completion, files are accepted and copied back to the media drive.

Files which are allocated to the vaapi node are processed with plugin 8 and there is a correctly transcoded file generated in the cache. On completion however, the file is listed in the staging area as `needs NVENC worker`. When the nvenc worker becomes free, it picks up this file but it does not get copied back to the media drive. Instead, the file is listed in the 'Transcode: Success/Not required' list with the status of `Not required`. Under the info button the status is ``☑ Stream analysis complete, no processing required.`` The transcoded file is left orphaned in the cache.

A similar thing happens if the nvenc plugin and vaapi plugin are reversed in order. Files given to the 7th plugin (vaapi in this case) are processed correctly and copied back to the media drive. Files given to the 8th plugin on the nvenc node go to the staging area with status `needs vaapi worker`. When the vaapi node is free, it picks the file up and marks it as done without copying back. The status in the history is ``File is already hevc or vp9 & in mkv.``.

The bug appears to be, that when tdarr goes back to check that all plugins are completed it uses the cached file to check if any further work needs to be done, but then doesn't pick up that it requires copying back. I have tested it several times and it is repeatable. I have also tested putting the transcode plugins in different locations in the stack, eg the nvenc plugin 3rd and vaapi 8th, but the same problem occurs.

**Second case:**
One node offline.

If the order of the plugin stack is such that the plugin for the available node comes before the plugin for the offline node, then the files are processed properly. eg, nvenc plugin is 7th, vaapi plugin is 8th.

If the plugin for the offline node comes before the one for the available node, then the file is listed in the staging area after transcoding with 'require x worker' where x is the type of the offline node. When that node becomes available, it starts working on the staged files, but the same error occurs as above - they are marked as finished without being copied back. Again, it is the order of the plugins which determines which one fails.

**Third case**
nvenc plugin replaced with CPU version: Tdarr_Plugin_MC93_Migz1FFMPEG_CPU. vaapi node has 1 gpu worker, second node has 1 cpu worker.

Plugin order is important again - if the cpu transcode is run first, it completes properly and copies. If it runs second however, there is a slightly different problem which may be a different bug. Files are listed in the staging area as 'require GPU worker', but when the GPU node becomes available, this file is ignored and no further processing of it occurs. It remains stalled in the staging area.

**Fourth case**
Both nodes enabled with hardware transcode plugins in stack. 1 CPU and 1 GPU worker enabled on each node, with CPU tasks enabled for GPU workers.

Any file which is handled by a CPU worker for the plugin prior to a GPU transcode gets stuck with 'require GPU worker' as the status. Clicking 'requeue' forces it to be processed again, however the outcome depends on which worker it gets assigned to. 

If it gets assigned to a GPU worker, it will transcode and then be subject to the first bug above - if the plugin for that GPU type is last, it gets falsely marked as complete and does not copy back.

If it gets assigned to the first GPU type in the plugin stack, it will complete correctly and copy back.

If it gets assigned to a CPU worker, it will again end up with the status 'require GPU worker'.


Sorry for the wall of text, but I hope it's useful.

**Comment by HaveAGitGat** [comment] 2021-02-10 07:47
Thanks,  I've updated 2.00.04 which fixes the first case. Wasn't able to check the others (can check them later) but they are most likely related to the first one.

**Comment by caiusseverus** [comment] 2021-02-13 16:41
I've tested 2.00.05 now.

The first case (1 vaapi node, 1 nvenc node, gpu workers only) is definitely fixed - all files were processed correctly and copied back with no orphaned files in the cache.

The second case (1 node offline) is also fixed. I've tried with either node offline, and files are all processed correctly and copied back.

These were the two major problems I was seeing, so that's a big improvement.

The remaining issue is when there are CPU workers involved. Having extra CPU workers enabled alongside GPU workers causes files to get stuck in staging with status 'waiting for GPU worker' - they never get picked up by available GPU workers. This is easily worked around by just not using CPU workers if you have GPU nodes available with 'enable CPU tasks' set. I guess there could be some edge case where someone uses a server without a GPU, and occasionally spins up a GPU node to help out, but I think for most people the issue can be avoided.

**Comment by HaveAGitGat** [comment] 2021-02-14 17:14
@caiusseverus finally managed to replicate that last issue. Just updated 2.00.05 which should fix the issue. Thanks

**Comment by caiusseverus** [comment] 2021-02-15 03:11
Files that have to wait for a GPU worker are now being processed OK and copied back so that is good. Sometimes transcoded files are not deleted from the cache after processing though.

If files are processed by CPU and GPU workers on the same node, then temporary TdarrCacheFile versions are all deleted once the final file is copied back. If the CPU worker and GPU worker are on different nodes, then the file that is left in the cache is the one used to generate the final version, ie the one generated by the previous CPU plugins.

eg, here is the cache after processing my test folder:
![image](https://user-images.githubusercontent.com/7763268/107901116-b88d8200-6f3a-11eb-9cf2-ed2316909128.png)

and here is the completed folder:

![image](https://user-images.githubusercontent.com/7763268/107901221-073b1c00-6f3b-11eb-8315-5b2946f3ad2b.png)



Something else I noticed, but I'm not sure if it's a bug or intended behaviour. Plugin order seems to be treated independently for CPU and GPU plugins - if you have a node with only a GPU worker available (ie with CPU tasks disabled), it will immediately start processing a file using the GPU transcode plugin regardless of where that plugin is in the stack, and the file will then wait for a CPU worker to become available to do the CPU plugins. That means that the plugin stack is processed out of order, which could be problematic if doing something like changing between container types. For example, transcoding from an mkv with ASS/SSA subtitles to mp4 might fail as mp4 does not support that format.

**Comment by HaveAGitGat** [comment] 2021-02-15 07:51
Nice that it's fixed.

And yes that is intended behaviour. Each worker checks all plugins to see if there's anything that can be processed else you'd end up in a situation with all GPU workers waiting for CPU tasks to finish which would defeat the point in having separate workers.

CPU and GPU tasks are done in their respective orders.

To have the plugin stack done exactly in order then you'd need to use only GPU workers and allow them to do CPU tasks.

**Comment by caiusseverus** [comment] 2021-02-15 14:38
That makes sense. Perhaps it would be a good idea to have the enable cpu tasks on gpu workers selected by default - I expect that the number of people who don’t want this would be small compared to those who do. Someone who doesn’t want it probably has something specific in mind and would be more likely to understand the limitation.

Either way It would be useful to have that behaviour noted in the documentation, or there’s likely to be people complaining that their transcodes are failing without realising why.

**Comment by HaveAGitGat** [comment] 2021-02-17 07:33
2.00.05 has a notice come up when the staging section reaches above 10 items:

```
                ⓘTip: To keep the staging section small, try enabling the following Node Options
                in the section above and only use Transcode GPU workers for transcoding:

              Allow GPU workers to do CPU tasks
              Always move failed transcodes to Transcode Error tab
```

Should be enough I think.

**Closed** 2021-02-18 17:31 UTC
Labels: fixed
