### ISSUE TITLE
Tdarr server setting to specify an alternative plugin response delimiter

### ISSUE THREAD

**Issue by jortan** [HaveAGitGat/Tdarr#461] opened 2021-07-09 09:01 UTC
**Is your feature request related to a problem? Please describe.**

There are a number of operations in ffmpeg that require a comma in their ffmpeg command.  When a plugin returns an ffmpeg preset to Tdarr that includes a comma, everything after the comma is truncated.  This seems to prevent the ability to create plugins that do any of the following:

Crop and resize
Use multiple filters
libx265 HDR encoding

**Describe the solution you'd like**

Add a Tdarr Server setting that allows a different delimiter to be specified (with a warning that Plugins would need to be modified to support this?)

Or can some way to escape the delimiter be added?

**Describe alternatives you've considered**

Not aware of any workarounds for this - some ffmpeg operations require a comma and it doesn't seem be possible to use these in Tdarr currently?

**Additional context**

partial response from plugin:

`crop=3840:1600:0:280,scale=-1:1920 -pix_fmt p010le`

Everything after the comma is truncated in the command Tdarr issues to the node:

`C:/tdarr/Tdarr_Node/node_modules/@ffmpeg-installer/win32-x64/ffmpeg.exe -c:v hevc_cuvid -i //server/folder/My File-2160p.mkv -map 0:v:0 -map 0:a -map 0:s? -filter:0 crop=3840:1600:0:280 //server/media/tdarr_temp/My File-2160p-TdarrCacheFile-B---QmrFz.mkv`

This issue is also described here:
https://github.com/HaveAGitGat/Tdarr/issues/456

and here:
https://www.reddit.com/r/Tdarr/comments/hlzolk/plugin_with_multiple_filters_comma_gets_parsed_by/

**Comment by HaveAGitGat** [comment] 2021-08-06 05:37
Duplicate of https://github.com/HaveAGitGat/Tdarr/issues/456

When using FFmpeg, you need to separate the input and output parameters with <io>. FFmpeg Examples:

```
-r 1<io>-r 24
<io>-sn -c:v copy -c:a copy
<io>-c:v lib265 -crf 23 -ac 6 -c:a aac -preset veryfast
<io>-map 0 -c copy -c:v libx265 -c:a aac
-c:v h264_cuvid<io>-c:v hevc_nvenc -preset slow -c:a copy
```

**Closed by HaveAGitGat** 2021-08-06 05:37 UTC
