### ISSUE TITLE
AV1 fails in Flows with A380

### ISSUE THREAD

**Issue by slimequeen3251** [HaveAGitGat/Tdarr#929] opened 2023-12-07 02:37 UTC
Hi, I have an A380 and setup a flow to encode with AV1. Using QSV it fails:

```
2023-12-07T02:22:03.478Z [av1_qsv @ 0x559a9035b540] Selected ratecontrol mode is unsupported
2023-12-07T02:22:03.478Z [av1_qsv @ 0x559a9035b540] Current frame rate is unsupported
2023-12-07T02:22:03.478Z [av1_qsv @ 0x559a9035b540] Current picture structure is unsupported
2023-12-07T02:22:03.478Z [av1_qsv @ 0x559a9035b540] Current resolution is unsupported
2023-12-07T02:22:03.478Z [av1_qsv @ 0x559a9035b540] Current pixel format is unsupported
2023-12-07T02:22:03.478Z [av1_qsv @ 0x559a9035b540] some encoding parameters are not supported by the QSV runtime. Please double check the input parameters.
2023-12-07T02:22:03.478Z [vost#0:0/av1_qsv @ 0x559a9035b000] Error initializing output stream: Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
2023-12-07T02:22:03.478Z Conversion failed!

```

Intel fixed this back in September: https://github.com/intel/media-driver/issues/1597

Debian 12
6.5.0-0.deb12.1-amd64
Docker with /dev/dri/renderD129 passed to it in compose.

**Comment by HaveAGitGat** [comment] 2023-12-07 05:10
Duplicate of https://github.com/HaveAGitGat/Tdarr/issues/902

**Closed by HaveAGitGat** 2023-12-07 05:10 UTC
