### ISSUE TITLE
Compare file size ratio of working file A / B

### ISSUE THREAD

**Issue by davidry** [HaveAGitGat/Tdarr#1013] opened 2024-05-28 10:30 UTC
### [[Feature Request - Permit Comparisons of Working Files]]
**Is your feature request related to a problem? Please describe.**
This is an attempt to Reduce Processing time of unnecessary files [Files that will get larger / stay the same]

**Describe the solution you'd like**
I'm looking for a plugin that would allow me to compare size ratios of  working file A with working file B  - perhaps an enhancement of the current "compare file size ratio" flow step [adding the ability to select source file ], or the ability to continue from a "Go to Flow"
Transcoding large media files can take quite some time depending on hardware

My hope is to get a solution that allows a 15 minute clip to be extracted, transcoded and compared .

This would allow me to breakout the transcode should I not see space benefits against the sample working files.

If the transcode shows savings, I can "set original file" and re-run my flow against the full file

**Describe alternatives you've considered**
- _Deploying an AIO Classic plugin_ - this seems needlessly time intensive with the need to fully re-write all transcoding steps into a single file
- _Utilizing the error / success of "Go to Flow"_ -  However there is no current way of continuing with the current flow, Unsure if this would override the original file
- _Calculating / Cutting a percentage of the frames in a custom transcode:_ - Inaccurate as different scenes will have different compression ratios

![image](https://github.com/HaveAGitGat/Tdarr/assets/32561343/6acc96a5-0740-45f1-9fcb-5e2da00fbe7e)
[HVEC_Tdarr_Plugin_075a_Transcode_Customisable.js.txt](https://github.com/HaveAGitGat/Tdarr/files/15475502/HVEC_Tdarr_Plugin_075a_Transcode_Customisable.js.txt)
[FlowExport.json](https://github.com/HaveAGitGat/Tdarr/files/15475580/FlowExport.json)

**Comment by HaveAGitGat** [comment] 2024-06-01 04:24
Hi, duplicate of https://github.com/HaveAGitGat/Tdarr/issues/571, will handle there ty

**Closed by HaveAGitGat** 2024-06-01 04:24 UTC

**Comment by HaveAGitGat** [comment] 2024-06-12 07:22
Added with flow plugin `Compare File Size Ratio Live`. Click `Update community plugins` on the classic plugins tab or will auto update within an hour or so.

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/6a9d81e6-5160-462f-bccc-edb6bd737fb8)
![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/0cffff4d-dac7-47d1-a6de-bda993f12739)

Can compare between either the estimated file size or the current file size of the output file.

```
  Compare either the estimated final size or current output size to the input size and 
  give an error if estimated final size or current size surpasses the threshold %.

  Works with 'FfmpegCommand', 'HandBrake Custom Arguments', 'Run Classic Transcode' and other flow plugins 
  that output a file.

  Can be placed anywhere before a plugin which outputs a new file.
```

**Comment by davidry** [comment] 2024-06-18 01:57
Thanks for that, I've updated my flows and its working great!

Would it be possible to get an error based off the live flow?
the unfortunate side effect of this plugin is it cancels on the transcoding step.
I am unable to determine if this failed due to file size or due to issues with the hardware filters for this particular stream


to workaround this at current, I am needing a second flow.

"Copy to Directory First" will transcode 20 seconds of Video.
- On success, it goes to the Main transcode flow, including this new Live Ratio checks
- On Failure, it re-runs a CPU version of the 20 second workflow. Either Terminating the overall file on failure or going to the CPU-intensive flow I have

This workaround catches 80% of the errors and queues the files appropriately.
the issue is when a hardware transcode fails after XX minutes of running. this still looks identical to the cancellation due to the live file size comparision

**Comment by HaveAGitGat** [comment] 2024-06-18 07:01
@davidry made this change here so can now use `Check Flow Error` to see if error was caused by the live size compare:
https://github.com/HaveAGitGat/Tdarr_Plugins/pull/669/files

```
  You can check if this plugin caused an error by using 'Check Flow Variable' and checking if 
  {{{args.variables.liveSizeCompare.error}}} is true.
```

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/1017a7c7-087f-496f-aae0-9ce255810f57)

![image](https://github.com/HaveAGitGat/Tdarr/assets/43864057/56384e1c-90ec-436b-96e8-536f7ce4cf5f)
