### ISSUE TITLE
Split Transcode workers in CPU and GPU

### ISSUE THREAD

**Issue by extremeshok** [HaveAGitGat/Tdarr#200] opened 2020-04-10 12:29 UTC
Currently there is only 1 setting for the workers, which is shared for both CPU and GPU.

This would allow a user to have:
X workers for GPU transcoding
and
Y workers for GPU transcoding.

And example would be a 32core system with 1 gpu, which could handle 28 CPU transcodes and 4GPU transcodes.

**Comment by HaveAGitGat** [comment] 2020-04-10 19:11
Hi, this seems like a duplicate of https://github.com/HaveAGitGat/Tdarr/issues/197

>handle 28 CPU transcodes and 4GPU transcodes.

Also I think there is some confusion with this. HandBrake and FFmpeg are multi-threaded, so running 28 CPU transcodes simultaneously would be detrimental to overall performance due to process overhead. You'd probably reach the optimum number of CPU transcodes at around 3-5. Likewise it would only take 1-2 GPU transcodes to saturate the hardware.

**Closed by HaveAGitGat** 2020-04-10 19:11 UTC

**Comment by extremeshok** [comment] 2020-04-27 14:17
Would not call it a duplicate of 197. After a much simpler solution. Have GPU workers and CPU workers.
 
Most machines have a GPU and a multicore CPU. The GPU will generally max out at 4 concurrent transcodes, and will use about 80% cpu on 8 vcpu. If one runs 3 transcodes it will use 6 vcpu on average. With 32 vpcu, the remaining 24cores can easily run 4 concurrent transcodes at 100% cpu usage.

On my exact hardware if i use GPU transcoding im left with 24cores sitting idle. If i do CPU transcoding, i am left with an idle quadro gpu.

Right now the only solution is to run 2 instances of tdarr , 1 doing CPU transcoding and 1 doing GPU transcoding.
