### ISSUE TITLE
Stats not updating after finishing transcode using Flows

### ISSUE THREAD

**Issue by moostmartijn** [HaveAGitGat/Tdarr#926] opened 2023-12-06 18:43 UTC
**Describe the bug**
Whenever a transcode is finished, the statistics should update, but they don't, in the latest version. The last working version for me was 2.11.01. 

**To Reproduce**
Start a transcode with flows and use the 'Move to directory' plugin. After and EVEN DURING transcoding, the numbers in the screenshot will stay at (0). 

**Expected behavior**
Statistics should update after transcoding finished. 

**Screenshots**
<img width="2288" alt="Schermafbeelding 2023-12-06 om 19 23 53" src="https://github.com/HaveAGitGat/Tdarr/assets/31592734/2406edf8-a0c6-4193-8a08-63be0c4524f8">

**Please provide the following information:**
- Config files  [can be found in /app/configs/ when using Docker or in the /configs folder next to Tdarr_Updater if not using Docker]
`Tdarr_Node_Config.json:`
```
{
  "nodeName": "SynologyNode",
  "serverIP": "0.0.0.0",
  "serverPort": "8266",
  "handbrakePath": "",
  "ffmpegPath": "",
  "mkvpropeditPath": "",
  "pathTranslators": [
    {
      "server": "",
      "node": ""
    }
  ],
  "logLevel": "INFO",
  "priority": -1,
  "cronPluginUpdate": ""
}

```

`Tdarr_Node_Config.json:`

```
{
  "serverPort": "8266",
  "webUIPort": "8265",
  "serverIP": "0.0.0.0",
  "handbrakePath": "",
  "ffmpegPath": "",
  "logLevel": "INFO",
  "mkvpropeditPath": "",
  "ccextractorPath": "",
  "openBrowser": true,
  "cronPluginUpdate": ""
}

```
- Job reports: https://docs.tdarr.io/docs/other/job-reports
*** Job reports are not found back because the numbers stay (0), there is no job report to be found in Tdarr after finishing the transcode.***

- Log files  [can be found in /app/logs/ when using Docker or in the /logs folder next to Tdarr_Updater if not using Docker]
[Logs.zip](https://github.com/HaveAGitGat/Tdarr/files/13590180/Logs.zip)

-Worker error [can be found on the 'Tdarr' tab by pressing the 'i' button on a failed item in the staged file section or in the transcode error section at the bottom]
Impossible with this bug.

 - OS: [e.g. Linux] : Linux, Synology NAS running 'container manager'
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 2.00.00] : 2.16.01

**Additional context**
I think this is the same issue: https://github.com/HaveAGitGat/Tdarr/issues/772 , this one was opened by me and closed as I should try flows. I now use flows, but after updating from `2.11.01` to the latest version, this issue re

This issue is probably the same bug: https://github.com/HaveAGitGat/Tdarr/issues/922

**Comment by HaveAGitGat** [comment] 2023-12-06 18:48
Seems duplicate of https://github.com/HaveAGitGat/Tdarr/issues/922 ty

**Closed by HaveAGitGat** 2023-12-06 18:48 UTC

**Comment by HaveAGitGat** [comment] 2023-12-06 18:53
Some steps here:
https://github.com/HaveAGitGat/Tdarr/issues/922#issuecomment-1843506882
