### ISSUE TITLE
Unable to access libraries tab.

### ISSUE THREAD

**Issue by WhooooFloorpie** [HaveAGitGat/Tdarr#294] opened 2020-10-26 13:43 UTC
Unable to access the libraries tab. Get a “oops, something went wrong message”. Refreshing page does not resolve issue. Have deleted container and started new container. Have restored backup. No fix.

**Comment by sienar1** [comment] 2020-10-28 19:00
Dupe of https://github.com/HaveAGitGat/Tdarr/issues/291

**Comment by HaveAGitGat** [comment] 2021-01-26 13:27
Fixed in v2. Instructions here:

http://tdarr.io/docs/

**Closed by HaveAGitGat** 2021-01-26 13:27 UTC
