### ISSUE TITLE
[Information Request/Flow Plugin Request] How to "Wait for GPU worker" with Flow?

### ISSUE THREAD

**Issue by javierlopeza** [HaveAGitGat/Tdarr#1009] opened 2024-05-23 04:59 UTC
I have a simple flow where I want to force transcode using GPU workers. This works with the old classic plugins stack, but now when switching to flow it allows CPU workers to do transcoding as well.

I know one can check the hardware type of the worker, but how can I then "loop" my flow so that it "waits" for a certain worker type?

Ideally I'd like to have a "Wait for GPU worker" kind of plugin that only passes once the type of the worker is hardware GPU (e.g. hevc_nvenc).

Thanks!

**Comment by HaveAGitGat** [comment] 2024-06-01 04:26
Practically a duplicate of https://github.com/HaveAGitGat/Tdarr/issues/748, will handle there ty

**Closed by HaveAGitGat** 2024-06-01 04:26 UTC

**Comment by HaveAGitGat** [comment] 2024-06-04 06:29
Will be possible in next version, can try dev version here: https://github.com/HaveAGitGat/Tdarr/issues/748#issuecomment-2146710875
